# Generated by Django 4.0 on 2024-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('about', models.TextField(db_index=True, verbose_name='Описание')),
                ('price', models.FloatField(db_index=True, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
